spring:
  application:
    name: fitnessTracker
  datasource:
    url: jdbc:h2:file:../fitness_db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
